server:
  port: 8071
spring:
    #dubbo的注册中心配置
  dubbo:
    #提供服务者姓名
    application: manage-service
    protocol:
      #dubbo协议
      name: dubbo
      port: 20881

    registry:
      #dubbo地址
      address: 192.168.188.15:2181
      #数据传输协议
      protocol: zookeeper
    #dubbo 的扫描路径 注解所在的包
    base-package: com.zhaoren.gmall.manage
      # provider 参数调优
    consumer:
      timeout: 10000
      check: false
  #mybatis 默认加载配置文件

  # 日志级别
logging:
   #可以进行 对日志级别的更改 debug 可看zookeeper心跳同步
   level:
     root: info