
#端口号
server:
  port: 8082

spring:
  dubbo:
    #项目发布的名称 不能相同
    application: car-web
    #协议名 端口号
    protocol:
      name: dubbo
      port: 20881
    #注册中心
    registry:
      address: 192.168.188.15:2181
      protocol: zookeeper
    #扫描注解所在的包
    base-package: com.zhaoren.gmall.gmall
    #dubbo 优化
    consumer:
      timeout: 10000
      check: false
# 日志等级
logging:
  level:
    root: info
